version: "3.7"

services:
  django:
    build: ./Personal-Blog
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - .volumes/static:/static
    env_file:
      - Personal-Blog/blog.env


  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - .volumes/static:/static
    ports:
      - "80:80"
    depends_on:
      - django
